export const SPARSE_RETRIEVER = Symbol('SPARSE_RETRIEVER');
export const DENSE_RETRIEVER = Symbol('DENSE_RETRIEVER');
export const LEGACY_RETRIEVER = Symbol('LEGACY_RETRIEVER');
export const RETRIEVAL_RUN_RECORDER = Symbol('RETRIEVAL_RUN_RECORDER');
export const INDEX_VERSION_RECORDER = Symbol('INDEX_VERSION_RECORDER');
